language: php

php:
  - '7.2'

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.5"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dareen;'
  - psql -c 'CREATE DATABASE dareen;' -U postgres

before_script:
  - composer install

script:
  - vendor/bin/phpunit
  - DB_CONNECTION=mysql DB_HOST=127.0.0.1 DB_PORT=3306 DB_DATABASE=dareen DB_USERNAME=travis DB_PASSWORD= vendor/bin/phpunit
  - DB_CONNECTION=pgsql DB_HOST=127.0.0.1 DB_PORT=5432 DB_DATABASE=dareen DB_USERNAME=postgres DB_PASSWORD= vendor/bin/phpunit
